/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-09-20 07:09:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import poly.dto.SggDTO;

public final class TunerRegister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("poly.dto.SggDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


	List<SggDTO> sList = (List<SggDTO>)request.getAttribute("sList");


      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" data-textdirection=\"ltr\" class=\"loading\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui\">\r\n");
      out.write("    <meta name=\"description\" content=\"Robust admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"admin template, robust admin template, dashboard template, flat admin template, responsive admin template, web app\">\r\n");
      out.write("    <meta name=\"author\" content=\"PIXINVENT\">\r\n");
      out.write("    <title>Register Page - Robust Free Bootstrap Admin Template</title>\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"/resources/app-assets/images/ico/apple-icon-60.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"/resources/app-assets/images/ico/apple-icon-76.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"/resources/app-assets/images/ico/apple-icon-120.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"/resources/app-assets/images/ico/apple-icon-152.png\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/resources/app-assets/images/ico/favicon.ico\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/png\" href=\"/resources/app-assets/images/ico/favicon-32.png\">\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("    <meta name=\"apple-touch-fullscreen\" content=\"yes\">\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"default\">\r\n");
      out.write("    <!-- BEGIN VENDOR CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/app-assets/css/bootstrap.css\">\r\n");
      out.write("    <!-- font icons-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/app-assets/fonts/icomoon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/app-assets/fonts/flag-icon-css/css/flag-icon.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/app-assets/vendors/css/extensions/pace.css\">\r\n");
      out.write("    <!-- END VENDOR CSS-->\r\n");
      out.write("    <!-- BEGIN ROBUST CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/app-assets/css/bootstrap-extended.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/app-assets/css/app.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/app-assets/css/colors.css\">\r\n");
      out.write("    <!-- END ROBUST CSS-->\r\n");
      out.write("    <!-- BEGIN Page Level CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/app-assets/css/core/menu/menu-types/vertical-menu.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/app-assets/css/core/menu/menu-types/vertical-overlay-menu.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/app-assets/css/pages/login-register.css\">\r\n");
      out.write("    <!-- END Page Level CSS-->\r\n");
      out.write("    <!-- BEGIN Custom CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/css/style.css\">\r\n");
      out.write("    <!-- END Custom CSS-->\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("  </head>\r\n");
      out.write("  <body data-open=\"click\" data-menu=\"vertical-menu\" data-col=\"1-column\" class=\"vertical-layout vertical-menu 1-column  blank-page blank-page\">\r\n");
      out.write("    <!-- ////////////////////////////////////////////////////////////////////////////-->\r\n");
      out.write("    <div class=\"app-content content container-fluid\">\r\n");
      out.write("      <div class=\"content-wrapper\">\r\n");
      out.write("        <div class=\"content-header row\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"content-body\"><section class=\"container\">\r\n");
      out.write("    <div class=\"col-md-8 offset-md-2 col-xs-12 box-shadow-2 p-0\">\r\n");
      out.write("\t\t<div class=\"card border-grey border-lighten-3 px-2 py-2 m-0\">\r\n");
      out.write("\t\t\t<div class=\"card-header no-border\">\r\n");
      out.write("\t\t\t\t<div class=\"card-title text-xs-center\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/resources/app-assets/images/logo/robust-logo-dark.png\" alt=\"branding logo\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<h6 class=\"card-subtitle line-on-side text-muted text-xs-center font-small-3 pt-2\"><span>조율사 회원가입</span></h6>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-body collapse in\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-block\">\r\n");
      out.write("\t\t\t\t\t\t<form name=\"form\" class=\"form\" action=\"/user/TunerRegProc.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"form-section\"><i class=\"icon-head\"></i> 기본 정보</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"user_name\">이름</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"user_name\" class=\"form-control\" placeholder=\"이름을 입력해주세요\" name=\"user_name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"id\">아이디</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"id\" class=\"form-control\" placeholder=\"아이디를 입력해주세요\" name=\"id\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"user_nick\">닉네임</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"projectinput2\" class=\"form-control\" placeholder=\"닉네임을 입력해주세요\" name=\"user_nick\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"email\">이메일</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"email\" class=\"form-control\" placeholder=\"이메일을 입력해주세요\" name=\"email\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"user_tel\">전화번호</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"user_tel\" class=\"form-control\" placeholder=\"전화번호를 입력해주세요\" name=\"user_tel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"password\">암호</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" id=\"password\" class=\"form-control\" placeholder=\"암호를 입력해주세요\" name=\"password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"verify_passwd\">암호 확인</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" id=\"verify_passwd\" class=\"form-control\" placeholder=\"암호를 재입력해주세요\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>성별</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"display-inline-block custom-control custom-radio ml-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"user_sex\" value=\"M\" checked=\"checked\" class=\"custom-control-input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"custom-control-indicator\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"custom-control-description ml-0\">남</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"display-inline-block custom-control custom-radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"user_sex\" value=\"F\" class=\"custom-control-input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"custom-control-indicator\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"custom-control-description ml-0\">여</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--조율사 경력 정보-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"form-section\"><i class=\"icon-clipboard4\"></i> 조율사 정보</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>자격증 등급</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"display-inline-block custom-control custom-radio ml-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"tuner_level\" value=\"0\" checked=\"checked\" class=\"custom-control-input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"custom-control-indicator\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"custom-control-description ml-0\">기능사</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"display-inline-block custom-control custom-radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"tuner_level\" value=\"1\" class=\"custom-control-input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"custom-control-indicator\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"custom-control-description ml-0\">산업기사</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>자격증 사진</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label id=\"projectinput7\" class=\"file center-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"file\" id=\"file\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"file-custom\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>프로필 사진</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label id=\"projectinput7\" class=\"file center-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"file\" id=\"file\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"file-custom\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"sosok\">소속</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"sosok\" name=\"affiliation\" class=\"form-control\" placeholder=\"예) ㅇㅇ피아노, ㅇㅇ대학교, 프리랜서 등\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"donationinput7\">한줄 소개</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea id=\"donationinput7\" rows=\"2\" class=\"form-control square\" name=\"tuner_comment\" placeholder=\"본인에 대한 소개를 한 줄로 작성해주세요\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"donationinput8\">이력</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea id=\"donationinput8\" rows=\"10\" class=\"form-control square\" name=\"tuner_exp\" placeholder=\"본인의 이력을 작성해주세요\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"form-section\"><i class=\"icon-clipboard4\"></i> 지역 정보</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"user_name\">근무지 주소</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"주소를 검색해주세요\" readonly name=\"addr\" id=\"addr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"sido_name\" id=\"sido_name\" hidden=\"hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"sgg_name\" id=\"sgg_name\" hidden=\"hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"emd_name\" id=\"emd_name\" hidden=\"hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"li_name\" id=\"li_name\" hidden=\"hidden\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"x_pos\" id=\"x_pos\" hidden=\"hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"y_pos\" id=\"y_pos\" hidden=\"hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary float-xs-right\" onclick=\"goPopup();\">주소검색</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"svc-area-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group svc-area\" style=\"margin-bottom:0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>활동지역을 선택해주세요</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select class=\"form-control\" onchange=\"getDetailSgg(this);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"00\">전국</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 for(SggDTO sDTO : sList){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=");
      out.print(sDTO.getSggCode());
      out.write('>');
      out.print(sDTO.getSggName() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
}
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"detail-checkboxes row\" style=\"margin-top:1em\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-4\">세부지역 없음</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"sgg_code\" class=\"sgg-detail\" value=\"00\" checked hidden=\"hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"text-xs-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-danger btn-sm\" onclick=\"delArea(this);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon-cross2\"></i> 지역 삭제\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-actions text-xs-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-sm\" onclick=\"addArea();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-check2 d-flex\"></i> 지역 추가\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-actions text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-check2 d-flex\"></i> 가입신청\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-warning mr-1 d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"icon-cross2\"></i> 취소\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ////////////////////////////////////////////////////////////////////////////-->\r\n");
      out.write("\r\n");
      out.write("    <!-- BEGIN VENDOR JS-->\r\n");
      out.write("    <script src=\"/resources/app-assets/js/core/libraries/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"/resources/app-assets/vendors/js/ui/tether.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"/resources/app-assets/js/core/libraries/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"/resources/app-assets/vendors/js/ui/perfect-scrollbar.jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"/resources/app-assets/vendors/js/ui/unison.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"/resources/app-assets/vendors/js/ui/blockUI.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"/resources/app-assets/vendors/js/ui/jquery.matchHeight-min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"/resources/app-assets/vendors/js/ui/screenfull.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"/resources/app-assets/vendors/js/extensions/pace.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <!-- BEGIN VENDOR JS-->\r\n");
      out.write("    <!-- BEGIN PAGE VENDOR JS-->\r\n");
      out.write("    <!-- END PAGE VENDOR JS-->\r\n");
      out.write("    <!-- BEGIN ROBUST JS-->\r\n");
      out.write("    <script src=\"/resources/app-assets/js/core/app-menu.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"/resources/app-assets/js/core/app.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <!-- END ROBUST JS-->\r\n");
      out.write("    <!-- BEGIN PAGE LEVEL JS-->\r\n");
      out.write("    <!-- END PAGE LEVEL JS-->\r\n");
      out.write("    <script>\r\n");
      out.write("    var svcAreaForm = document.getElementById(\"svc-area-group\").innerHTML;\r\n");
      out.write("   \t\r\n");
      out.write("    // 상세 시군구코드 구하기\r\n");
      out.write("    function getDetailSgg(elem){\r\n");
      out.write("\t\tvar query = {sidoCode : elem.value};\r\n");
      out.write("\t\tconsole.log(\"sidocode : \" + elem.value);\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"/addr/GetSgg.do\",\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\tdata:query,\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\telem.parentElement.getElementsByClassName('detail-checkboxes')[0].innerHTML = data;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("   \t}\r\n");
      out.write("   \t\r\n");
      out.write("    // 전체 선택/취소\r\n");
      out.write("   \tfunction toggleAll(elem){\r\n");
      out.write("   \t\tvar checkboxes = elem.parentElement.parentElement.getElementsByClassName('sgg-detail');\r\n");
      out.write("\t\tfor(var i=1; i < checkboxes.length; i++){\r\n");
      out.write("\t\t\tvar checkbox = checkboxes[i];\r\n");
      out.write("\t\t\tcheckbox.checked = elem.checked;\r\n");
      out.write("\t\t\tcheckbox.disabled = elem.checked;\r\n");
      out.write("\t\t\tcheckbox.name = elem.checked ? \"\" : \"sgg_code\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("   \t}\r\n");
      out.write("    \r\n");
      out.write("   \tfunction addArea(){\r\n");
      out.write("   \t\t$('#svc-area-group').append(svcAreaForm);\r\n");
      out.write("   \t}\r\n");
      out.write("   \t\r\n");
      out.write("   \tfunction delArea(elem){\r\n");
      out.write("   \t\tif(document.getElementsByClassName('svc-area').length == 1){\r\n");
      out.write("   \t\t\talert(\"최소 한 개의 활동지역은 있어야 합니다.\");\r\n");
      out.write("   \t\t\treturn;\r\n");
      out.write("   \t\t}\r\n");
      out.write("   \t\t\t\r\n");
      out.write("   \t\telem.parentElement.parentElement.remove();\r\n");
      out.write("   \t}\r\n");
      out.write("   \t\r\n");
      out.write("   \t// 모두 체크 되었는지 확인\r\n");
      out.write("   \tfunction checkAllChecked(elem){\r\n");
      out.write("   \t\tvar subDetails = elem.parentElement.parentElement.getElementsByClassName('sub-detail');\r\n");
      out.write("   \t\tvar allChecked = true;\r\n");
      out.write("   \t\tfor(var i = 0; i < subDetails.length; i++){\r\n");
      out.write("   \t\t\tallChecked = allChecked && subDetails[i].checked;\r\n");
      out.write("   \t\t}\r\n");
      out.write("   \t\tif(allChecked){\r\n");
      out.write("   \t\t\telem.parentElement.parentElement.getElementsByClassName('select-all')[0].click();\r\n");
      out.write("   \t\t}\r\n");
      out.write("   \t}\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("     <!-- addrInput popup -->\r\n");
      out.write("    <script language=\"javascript\">\r\n");
      out.write("\t\tfunction goPopup(){\r\n");
      out.write("\t\t\t// 호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(http://www.juso.go.kr/addrlink/addrCoordUrl.do)를 호출하게 됩니다.\r\n");
      out.write("\t\t    var pop = window.open(\"/addr/AddrPopup.do\",\"pop\",\"width=570,height=420, scrollbars=yes, resizable=yes\"); \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction jusoCallBack(roadFullAddr,roadAddrPart1,addrDetail,roadAddrPart2,engAddr, jibunAddr, zipNo, admCd, rnMgtSn, bdMgtSn\r\n");
      out.write("\t\t\t\t\t\t\t\t, detBdNmList, bdNm, bdKdcd, siNm, sggNm, emdNm, liNm, rn, udrtYn, buldMnnm, buldSlno, mtYn, lnbrMnnm, lnbrSlno\r\n");
      out.write("\t\t\t\t\t\t\t\t, emdNo, entX, entY){\r\n");
      out.write("\t\t\t// 팝업페이지에서 주소입력한 정보를 받아서, 현 페이지에 정보를 등록합니다.\r\n");
      out.write("\t\t\tdocument.form.addr.value = roadFullAddr.replace(\"& #40;\", \"(\").replace(\"& #41;\", \")\");\r\n");
      out.write("\t\t\tdocument.form.sido_name.value = siNm;\r\n");
      out.write("\t\t\tdocument.form.sgg_name.value = sggNm;\r\n");
      out.write("\t\t\tdocument.form.emd_name.value = emdNm;\r\n");
      out.write("\t\t\tdocument.form.li_name.value = liNm;\r\n");
      out.write("\t\t\tdocument.form.x_pos.value = entX;\r\n");
      out.write("\t\t\tdocument.form.y_pos.value = entY;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
